version: '3.9' 

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: back
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      DB_HOST: db                   
      DB_USER: ${POSTGRES_USER}     
      DB_PASSWORD: ${POSTGRES_PASSWORD} 
      DB_NAME: ${POSTGRES_DB}       
  alembic:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: alembic
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["alembic", "history"]
    depends_on:
      - db  # Ждет, пока PostgreSQL станет доступен
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: